apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: eks-app
spec:
  selector:
    matchLabels:
      app: eks-app
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: eks-app
        tier: frontend
    spec:
      containers:
      - name: eks-app
        image: ${REPOSITORY_TAG}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eks-app
spec:
  selector:
    app: eks-app
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
